export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_REQUEST_SUCCESSS = "LOGIN_REQUEST_SUCCESSS"
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE"

export const REGISTER_USER_IN_LOGIN = "REGISTER_USER_IN_LOGIN"
export const LOGIN_FOR_NAVIGATE = "LOGIN_FOR_NAVIGATE"

