export const PRODUCTS_DATA = "PRODUCTS_DATA"
export const PRODUCTS_DATA_SUCCESS = "PRODUCTS_DATA_SUCCESS"
export const PRODUCTS_DATA_FAILURE = "PRODUCTS_DATA_FAILURE"

export const IMAGES_DATA = "IMAGES_DATA"
export const IMAGES_DATA_SUCCESS = "IMAGES_DATA_SUCCESS"
export const IMAGES_DATA_FAILURE = "IMAGES_DATA_FAILURE"

